Super strange bug happening here:
On Version 0.4.0-dev+4133 running julia -L runtests.jl results in:

Could not instantiate instance for type encoding the trait Traits.Collection{Dict{Int64,V}}.
This usually indicates that something is amiss with the @traitdef
or that one of the generic functions is not defined.
The error was: ArgumentError("invalid type for argument #s73 in method definition for __eltype at null:0")
ERROR: LoadError: LoadError: test failed: istrait(Assoc{c},verbose=true)
 in expression: istrait(Assoc{c},verbose=true)
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in anonymous at no file:102
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
 in process_options at ./client.jl:260
 in _start at ./client.jl:401
while loading .julia/v0.4/Traits/test/traitdef.jl, in expression starting on line 101
while loading .julia/v0.4/Traits/test/runtests.jl, in expression starting on line 39

However, it goes away with a @show somewhere in isfitting.  Super
strange bug.